    _     _   _  _____   ___       ____   ___   __  __  __  __     _     _   _  ____      ____   _   _  _   _  _   _  _____  ____  
   / \   | | | ||_   _| / _ \     / ___| / _ \ |  \/  ||  \/  |   / \   | \ | ||  _ \    |  _ \ | | | || \ | || \ | || ____||  _ \ 
  / _ \  | | | |  | |  | | | |   | |    | | | || |\/| || |\/| |  / _ \  |  \| || | | |   | |_) || | | ||  \| ||  \| ||  _|  | |_) |
 / ___ \ | |_| |  | |  | |_| |   | |___ | |_| || |  | || |  | | / ___ \ | |\  || |_| |   |  _ < | |_| || |\  || |\  || |___ |  _ < 
/_/   \_\ \___/   |_|   \___/     \____| \___/ |_|  |_||_|  |_|/_/   \_\|_| \_||____/    |_| \_\ \___/ |_| \_||_| \_||_____||_| \_\

# Add commands below
on-start:
  - time set day
